version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
  - watawuwu

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
  - watawuwu
