version: 1
update_configs:
- package_manager: "rust:cargo"
  directory: "/"
  update_schedule: "weekly"
  default_reviewers:
  - "watawuwu"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "all"
- package_manager: "docker"
  directory: "/"
  update_schedule: "weekly"
  default_reviewers:
  - "watawuwu"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "all"

