name: Security audit

on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup code
        uses: actions/checkout@v2

      - name: Check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
