name: Release

on:
  push:
    tags:
     - '*.*.*'

env:
  NAME: bump

jobs:
  create_github_release:
    name: Create Github release
    runs-on: ubuntu-latest

    steps:
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Output release URL file
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt

    - name: Save release URL file for publish
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: release_url.txt

  build_and_publish:
    name: Build and publish
    needs: [create_github_release]
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-linux-musl
        - x86_64-apple-darwin
        - x86_64-pc-windows-msvc
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: x86_64-pc-windows-msvc
          os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup code
      uses: actions/checkout@v2

    - name: Get tag
      id: get_tag
      uses: olegtarasov/get-tag@v2

    - name: Install musl tools
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: |
        sudo apt install -qq -y musl-tools --no-install-recommends

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --release --target=${{ matrix.target }}

    - name: Create artifact
      shell: bash -x {0}
      run: |
        tar -acvf ${{ env.NAME }}-${{ steps.get_tag.outputs.tag }}-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release ${{ env.NAME }}{,.exe}
        set -e
        ls -la ${{ env.NAME }}-${{ steps.get_tag.outputs.tag }}-${{ matrix.target }}.tar.gz

    - name: Load release URL file
      uses: actions/download-artifact@v1
      with:
        name: release

    - name: Get release file name & upload URL
      id: get_release_info
      shell: bash
      run: |
        upload_url=$(cat release/release_url.txt)
        echo "::set-env name=UPLOAD_URL::$upload_url"

    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: ./${{ env.NAME }}-${{ steps.get_tag.outputs.tag }}-${{ matrix.target }}.tar.gz
        asset_name: ${{ env.NAME }}-${{ steps.get_tag.outputs.tag }}-${{ matrix.target }}.tar.gz
        asset_content_type: application/gzip
